version: "3.1"

services:
  db:
    container_name: db
    image: mysql:5.7
    command: --init-file /docker-entrypoint.initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: asiago
    volumes:
      - ./sqls:/docker-entrypoint.initdb.d
    networks:
      - shared_network
    ports:
      - "3306:3306"
  app:
    container_name: nicely_app
    command: pytest --cov-report term-missing --cov=.
    #command: python main.py
    restart: on-failure:5
    #depends_on:
    #  - db
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: asiago
      FAKE_COMMIT_HASH: cd7daa643ffa505ae3b465beaa583df42246f4f2
      FLASK_ENV: development
    volumes:
      - ./:/app
    build:
        context: .
    networks:
      - shared_network
    ports:
      - "5000:5000"
networks:
  shared_network: